Issue 12 provide a route to upload files
diffal/diffal pull request #21
Opened 2022-02-27 12:29 UTC by we4netbot

سلام ماژول آپلود اکی شد

تست هم شد فایل آپلود میشه و مشخصاتی از جمله اسم اصلی اسم نهایی آدرس یا همون پچ و تایپ فایل برمیگردونه
3000:upload/single   ------آپلود میکنه تو ---->   files/upload

آدرس محل آپلود رو با متغییر محیطی دادم اما نمیخوند

منتظرم مشکلاتم رو بگید تا برطرف کنم ...

2022-02-27 15:20 UTC, Rzix commented
حتی اگه مسیر رو دستی(خارج از .env) بزاری باز هم توی مسیره نوشته شده آپلود نمیشه؟

2022-02-28 17:54 UTC, fahimi85 commented
First of all, congratulations on completing this issue. I'm checking... @we4netbot

2022-03-01 07:54 UTC, mostafa8026 commented on src/upload/upload.controller.ts
> +  uploadSingle(@UploadedFile() file: Express.Multer.File) {
خب وقتی از متغیر محیطی استفاده‌ای نکردی... چه انتظاری داری؟  تو کلاس بیشتر توضیح میدم

2022-03-01 07:55 UTC, mostafa8026 commented on src/main.ts
> +  app.enableCors();
اینو چرا اضافه کردی؟ دلیلش رو میدونی؟

2022-03-01 07:56 UTC, mostafa8026 commented on src/upload/upload.module.ts
> +    MulterModule.register({
مگه registerAsync نداره؟

2022-03-01 08:43 UTC, fahimi85 commented on src/upload/upload.module.ts
> +    MulterModule.register({
![Upload](https://user-images.githubusercontent.com/96005734/156135009-16799f22-f3b4-464f-9573-6a9924851926.jpg)

2022-03-01 08:45 UTC, fahimi85 commented on src/upload/upload.module.ts
> +    MulterModule.register({
Do you have a compelling reason to use the registration? @we4netbot

2022-03-01 08:48 UTC, fahimi85 requested changes
I want to use your module. Can you explain more about how to use it? I used it but it gives an error. Maybe I'm not using it right. @we4netbot

2022-03-01 09:03 UTC, miladworkac requested changes
This file is not running properly, please request it again after recovery

2022-03-01 16:47 UTC, alieidelkhani commented on src/upload/upload.controller.spec.ts
> +  beforeEach(async () => {
if i have the right mind mr mostafavi told us to use beforeAll instead of beforeEach so that the test takes less time to work!

2022-03-05 07:32 UTC, fahimi85 submitted a review, later dismissed
it's ok. @we4netbot

2022-03-05 13:32 UTC, miladworkac approved these changes

2022-03-05 21:37 UTC, alieidelkhani approved these changes

2022-03-06 07:34 UTC, Rzix approved these changes

2022-03-08 08:44 UTC, mostafa8026 commented
@we4netbot 
برای رفع مشکل نام فایل باید یه سرویسی برای آپلودت داشته باشی که توی اون سرویس با توجه به اطلاعات فایلی که multer بهت میده. نام صحیح فایل رو در بیاری. یه چیزایی شبیه به این:

```
upload(file: Express.Multer.File): UploadFileDto {
    let fileName = file.originalname.substr(0, file.originalname.lastIndexOf('.'));
    const fileExtension = file.originalname.substr(file.originalname.lastIndexOf('.') + 1);
    if (fileExtension) {
      fileName += '.' + fileExtension;
    }
    fileName = file.filename + '-' + fileName;
    renameSync(file.path, this.uploadPath + fileName);
    return {
      hash: file.filename,
      fileName: fileName,
      displayName: file.originalname,
      mimeType: file.mimetype,
      size: file.size,
    };
  }
```

:د بالا یه مثال هست. تو خودت باید با توجه به مسیر آپلود که از تنظیمات متغیرهای محیطی میاد درست بخونی

2022-03-08 09:40 UTC, miladworkac submitted a review, later dismissed

2022-03-09 09:54 UTC, mostafa8026 submitted a review, later dismissed
Looks good to me for now.

2022-03-09 11:03 UTC, mostafa8026 commented
کانفلیکت خورده. یه بررسی کن. برای متغیرهای محیطی هم میتونی خودت دستی تو تست 
process.env 
رو مقداردهی کنی.

2022-03-09 11:30 UTC, fahimi85 submitted a review, later dismissed

2022-03-09 13:15 UTC, miladworkac approved these changes

2022-03-09 13:16 UTC, fahimi85 approved these changes

2022-03-09 13:16 UTC, mostafa8026 approved these changes

2022-03-09 13:16 UTC, merged