fix(backend): fix category child remove
diffal/diffal pull request #50
Opened 2022-03-11 16:49 UTC by mostafa8026

یه مشکلی خود typeorm موقع حذف داره که برای ستون‌های uuid مشکل میخوره. یه issu‌ براشون ثبت کردم که پایین لینکش رو گذاشتم. فعلا این پول ریکوئست مشکلی که توی #9  گزارش شده بود رو حل می‌کنه. @Rzix حتما دقیق ریویو کنید. یه سری اشکالات دیگه هم داشتی که رفع کردم.
https://github.com/typeorm/typeorm/issues/8743

2022-03-11 20:02 UTC, fahimi85 approved these changes

2022-03-11 20:06 UTC, fahimi85 requested changes
![123](https://user-images.githubusercontent.com/96005734/157951369-fbe4190b-485f-4830-beef-54081ea2589d.png)
Also in postEntity id is not number  Because of  uuid. @mostafa8026 @alieidelkhani 
& in postService  &  its test  & post.repository, all type of id should be changed to string.

2022-03-12 07:53 UTC, Rzix commented
استاد فکر کنم توی pull request که سر کلاس انجام دادیم اشتباهی شده همه تغییراتم برگشتن به حالتای اولیه

2022-03-12 07:53 UTC, Rzix commented
@mostafa8026

2022-03-12 08:09 UTC, mostafa8026 commented
امروز دقیقتر چک میکنیم.

2022-03-12 12:39 UTC, miladworkac submitted a review, later dismissed

2022-03-12 13:02 UTC, merged